Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519
    AddKeysToAgent yes
    {{ if eq .chezmoi.os "darwin" }}UseKeychain yes{{ end }}

Host *
    AddKeysToAgent yes
    {{ if eq .chezmoi.os "darwin" }}UseKeychain yes{{ end }}
    IdentityFile ~/.ssh/id_ed25519
