# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: Mine
    filters: is:open author:@me sort:updated-desc
  - title: Review Requested
    filters: is:open review-requested:@me sort:updated-desc
  - title: All
    filters: is:open sort:updated-desc

issuesSections:
  - title: Mine
    filters: is:open author:@me sort:updated-desc
  - title: Assigned
    filters: is:open assignee:@me sort:updated-desc
  - title: All
    filters: is:open sort:updated-desc

defaults:
  view: prs
  refetchIntervalMinutes: 5
  layout:
    prs:
      repoName:
        hidden: false
      base:
        hidden: true
  preview:
    open: true
    width: 60
  prsLimit: 20
  issuesLimit: 20

theme:
  colors:
    text:
      primary: "#e0def4"
      secondary: "#c4a7e7"
      inverted: "#191724"
      faint: "#6e6a86"
      warning: "#f6c177"
      success: "#31748f"
    background:
      selected: "#26233a"
    border:
      primary: "#908caa"
      secondary: "#403d52"
      faint: "#26233a"
